name: Publish Docker Image on Tag

on:
  push:
    tags:
      - 'v*'  # Triggers on any tag that starts with 'v'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Run build script
      run: |
        chmod +x ./build.sh
        ./build.sh

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        provenance: true
        sbom: true
        tags: |
          ${{ secrets.DOCKERHUB_ORG }}/open-rl-gymnasium-grpc-server:${{ steps.tag.outputs.TAG }}
          ${{ secrets.DOCKERHUB_ORG }}/open-rl-gymnasium-grpc-server:latest
